// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caffe2_legacy.proto

#ifndef PROTOBUF_caffe2_5flegacy_2eproto__INCLUDED
#define PROTOBUF_caffe2_5flegacy_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace caffe2 {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_caffe2_5flegacy_2eproto();
void protobuf_AssignDesc_caffe2_5flegacy_2eproto();
void protobuf_ShutdownFile_caffe2_5flegacy_2eproto();


enum LegacyPadding {
  NOTSET = 0,
  VALID = 1,
  SAME = 2,
  CAFFE_LEGACY_POOLING = 3
};
bool LegacyPadding_IsValid(int value);
const LegacyPadding LegacyPadding_MIN = NOTSET;
const LegacyPadding LegacyPadding_MAX = CAFFE_LEGACY_POOLING;
const int LegacyPadding_ARRAYSIZE = LegacyPadding_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace caffe2

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_caffe2_5flegacy_2eproto__INCLUDED
